Repository ircv3/ircv3-specifications, pull requests merged in 2020-01, with the labels that each got.

#400 [labeled-response] Make batch a hard dependency
  extensions/labeled-response.md
Labels: batch

#403 Ratify labeled-response
  extensions/labeled-response.md
Labels: Ratify, tags

#371 Cap Clarifications
  core/capability-negotiation.md
Labels: errata, protocol
